<a href="https://colab.research.google.com/github/andmarin/CS767_Assignment2/blob/main/Assg2_NN_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Copyright 2019 The TensorFlow Authors. Edited by Eric Braude

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TensorFlow 2 quickstart, edited by Eric Braude

I recommend runniing on Colab.
<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/quickstart/beginner"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This uses [Keras](https://www.tensorflow.org/guide/keras/overview) to:

1. Build a neural network that classifies images.
2. Train this neural network.
3. And, finally, evaluate the accuracy of the model.


This is a [Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) notebook file. Python programs are run directly in the browser—a great way to learn and use TensorFlow. To follow this tutorial, run the notebook in Google Colab by clicking the button at the top of this page.

1. In Colab, connect to a Python runtime: At the top-right of the menu bar, select *CONNECT*. (I did not need to do this- EB)
2. To run all the notebook code cells (i.e., not just one at a time): Select *Runtime* > *Run all*.

AS NEEDED ... Download and install TensorFlow 2. Import TensorFlow into your program:

Note: Upgrade `pip` to install the TensorFlow 2 package. See the [install guide](https://www.tensorflow.org/install) for details.

In [2]:
import tensorflow as tf

Load and prepare the [MNIST dataset](http://yann.lecun.com/exdb/mnist/). Visualize: https://www.tensorflow.org/datasets/catalog/mnist Convert the samples from integers to floating-point numbers:

TEST UPLOAD

In [ ]:
# INTENT: Load the MNIST data and show it, raw, on the monitor

mnist = tf.keras.datasets.mnist # a data set known to Keras/TensorFlow
# mnist.load_data() produces a pair of input/output tensors: one for training
# and one for testing.
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print("===========y_train===========")
print(tf.shape(y_train))  # format of output data: 60K records 0-9
print(y_train)  # for inspection
x_train, x_test = x_train / 255.0, x_test / 255.0  # scale down input
print("===========x_train===========")
print(tf.shape(x_train))
print("===========x_train element 0 (28 rows of 28 gray values)===========")
print(x_train[0])  # for inspection

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
===========y_train===========
tf.Tensor([60000], shape=(1,), dtype=int32)
[5 0 4 ... 5 6 8]
===========x_train===========
tf.Tensor([60000    28    28], shape=(3,), dtype=int32)
===========x_train element 0 (28 rows of 28 gray values)===========
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.     

Build the `tf.keras.Sequential` model (object) by stacking layers.

https://www.tensorflow.org/api_docs/python/tf/keras/Sequential

In [ ]:
model = tf.keras.models.Sequential([  # layer format for the neural net
  # each pixel (grayscale value) mapped to one of 784 nodes
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  # fully connected to hidden layer with relu
  tf.keras.layers.Dense(128, activation='relu'),
  # Dropout layer randomly sets its input units to 0 at 20% rate at each training step
  # The other inputs are scaled up by 1/0.8 so sum over all inputs is unchanged
  # Illustrative figure: http://laid.delanover.com/wp-content/uploads/2018/02/dropout.png
  # (Doc: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout)
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10) # e.g., output #7 = degree to which the output is 7
])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


The model returns a vector of "[logits](https://developers.google.com/machine-learning/glossary#logits)" scores, one for each class--"raw, unnormalized values that will eventually be used to calculate probabilities." In other words, a tensor where the highest value indicates the most likely output.

https://en.wikipedia.org/wiki/Logit

model() acts like a function, returning the neural net object.

In [ ]:
print("===========first element of x_train (29 rows)===========")
print(x_train[:1])

predictions = model(x_train[:1]).numpy() # numpy() converts the tensor output
print("===========untrained output of first training set input===========")
print(predictions)  # expect random output, probably not favoring one digit

===========first element of x_train (29 rows)===========
[[[0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0. 

The `tf.nn.softmax` function converts these logits to "probabilities" for each class (summing to 1).

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09994353, 0.08068919, 0.13104558, 0.09197003, 0.13230649,
        0.07494854, 0.08247142, 0.10121606, 0.10868694, 0.09672229]],
      dtype=float32)

Note: It is possible to bake this `tf.nn.softmax` in as the activation function for the last layer of the network. While this can make the model output more directly interpretable, this approach is discouraged as it's impossible to
provide an exact and numerically stable loss calculation for all models when using a softmax output.

The `losses.SparseCategoricalCrossentropy` loss takes a vector of logits and a `True` index and returns a scalar loss for each example. (https://docs.google.com/document/d/16v7AIXuwAwdOZxorwSDXKRGzJA8jUYAR_D-QJTxEiyA/edit?usp=sharing) We give it a short name.

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This loss is equal to the negative log probability of the true class. It is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to `-tf.math.log(1/10) ~= 2.3`.

Recall that y_train is the target (desired output) tensor. We select the first element.

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.5909536

In [ ]:
# Put together the NN with training process, loss, and means of evaluation.
# 'accuracy' = proportion of correct predictions vs. total number of cases
model.compile(optimizer='adam',  # a process (we'll describe) for adjusting weights
              loss=loss_fn,
              metrics=['accuracy'])  # how we'll evaluate the epochs (iterations)

The `Model.fit` method adjusts the model's parameters to minimize the loss:

In [ ]:
# Train the net with (just) 5 epochs
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8616 - loss: 0.4771
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9550 - loss: 0.1560
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9653 - loss: 0.1111
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9703 - loss: 0.0913
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9758 - loss: 0.0784


The `Model.evaluate` method checks the model's performance, usually on a "[Validation-set](https://developers.google.com/machine-learning/glossary#validation-set)" or "[Test-set](https://developers.google.com/machine-learning/glossary#test-set)".

In [ ]:
# Accuracy = fraction of correct test pairs
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9751 - loss: 0.0845


[0.08451878279447556, 0.9750999808311462]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the [TensorFlow tutorials](https://www.tensorflow.org/tutorials/).

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
print("===========y_test element 0===========")
print(y_test[0])  # for inspection
probability_model(x_test[:5])  # on first 5 input images in test set

===========y_test element 0===========
7


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.81920171e-07, 1.43967324e-10, 9.17742625e-07, 7.04908007e-06,
        1.09304801e-10, 3.07034185e-08, 6.71379575e-15, 9.99989748e-01,
        2.01779599e-07, 1.91317599e-06],
       [1.22473347e-08, 4.17247356e-05, 9.99947548e-01, 1.05010331e-05,
        1.20396841e-17, 3.57903716e-08, 4.10018650e-08, 6.57853383e-13,
        1.89476097e-07, 2.44745240e-14],
       [2.55723444e-06, 9.97571886e-01, 2.28855293e-04, 2.25356980e-05,
        4.33193018e-05, 9.67596861e-06, 3.53763826e-05, 1.40157784e-03,
        6.83641469e-04, 6.79335017e-07],
       [9.99465883e-01, 1.95409129e-08, 2.02595475e-04, 1.47611736e-08,
        7.24376264e-07, 1.35770888e-05, 2.37919176e-06, 2.93948775e-04,
        2.52883012e-08, 2.09264181e-05],
       [2.01283751e-06, 1.15117724e-11, 2.91570977e-05, 1.08429923e-08,
        9.98972178e-01, 4.37760349e-07, 2.01722082e-06, 9.04857443e-05,
        3.79141341e-07, 9.03292093e-04]], dtype=float32)>